###############################################################################
# Equation Scoring Engine
# Copyright (c) 2013 American Institutes for Research
# 
# Distributed under the AIR Open Source License, Version 1.0
# See accompanying file AIR-License-1_0.txt or at 
# https://bitbucket.org/sbacoss/eotds/wiki/AIR_Open_Source_License
###############################################################################

DICTIONARY = {
    u"\u00D7" : u"*",
    u"\u00F7" : u"/",
    u"\u2212" : u"-",
    u"\u2215" : u"/",
    u"\u2217" : u"*",
    u"\u2061" : u"",
    u"\u221E" : u"oo",
    u"\u2223" : u"|",
    u"\u25fb" : u"box",
    u"\u03B1" : u"alpha",
    u"\u03B2" : u"beta",
    u"\u03B3" : u"gamma",
    u"\u03B4" : u"delta",
    u"\u03B5" : u"epsilon",
    u"\u03F5" : u"epsilon",
    u"\u03B6" : u"zeta",
    u"\u03B7" : u"eta",
    u"\u03B8" : u"theta",
    u"\u03B9" : u"iota",
    u"\u03BA" : u"kappa",
    u"\u03BB" : u"lambda",
    u"\u03BC" : u"mu",
    u"\u03BD" : u"nu",
    u"\u03BE" : u"xi",
    u"\u03BF" : u"omicron",
    u"\u03C0" : u"pi",
    u"\u03C1" : u"rho",
    u"\u03C3" : u"sigma",
    u"\u03C4" : u"tau",
    u"\u03C5" : u"upsilon",
    u"\u03C6" : u"phi",
    u"\u03C7" : u"chi",
    u"\u03C8" : u"psi",
    u"\u03C9" : u"omega",
    u"\u0393" : u"Gamma",
    u"\u0394" : u"Delta",
    u"\u0398" : u"Theta",
    u"\u039B" : u"Lambda",
    u"\u039E" : u"Xi",
    u"\u03A0" : u"Pi",
    u"\u03A3" : u"Sigma",
    u"\u03A5" : u"Upsilon",
    u"\u03A6" : u"Phi",
    u"\u03A8" : u"Psi",
    u"\u03A9" : u"Omega",
    u"arcsin" : u"asin",
    u"arccos" : u"acos",
    u"arctan" : u"atan",
    u"i" : u"I",
}